baseURL = '/'
languageCode = 'en-us'
title = "K_Lar's website"
theme = "hugo-theme-monochrome"
footer = "Copyright © 2022-2023 by K_Lar"
enableEmoji = true

[params]
author = "K_Lar" # default: no author `meta` tag
description = 'My personal website'
enable_toc = true # default: true
enable_collapsible_toc = true # default: false
enable_collapsible_changelogs = true # default: false
enable_site_search = true # default: false
  [param.syntax_highlight]
  lib = "prism.js" # "builtin" | "prism.js" (default: "builtin")
    [param.syntax_highlight.builtin]
    enable_code_copy = true # default: true
    enable_line_no = false # default: true

[menu]
  [[menu.navbar]]
  identifier = "blog"
  name = "blog"
  title = "blog"
  url = "blog/"
  weight = -100

  [[menu.navbar]]
  identifier = "projects"
  name = "projects"
  url = "projects/"
  weight = 100

  [[menu.navbar]]
  identifier = "categories"
  name = "categories"
  url = "/categories/"
  weight = 80

[outputs]
home = ["HTML", "RSS", "JSON"]
