baseURL = '/'
languageCode = 'en-us'
title = "klarspace"
theme = "hugo-theme-monochrome"
enableEmoji = true

[params]
author = "K_Lar" # default: no author `meta` tag
description = 'My personal website'
footer = "Copyright © 2022-2023 by K_Lar"
enable_toc = true # default: true
enable_collapsible_toc = true # default: false
enable_collapsible_changelogs = true # default: false
enable_site_search = true # default: false
  [param.syntax_highlight]
  lib = "prism.js" # "builtin" | "prism.js" (default: "builtin")
    [param.syntax_highlight.builtin]
    enable_code_copy = true # default: true
    enable_line_no = false # default: true

[menu]
  [[menu.navbar]]
  identifier = "blog"
  name = "blog"
  title = "blog"
  url = "/blog/"
  weight = -100

  [[menu.navbar]]
  identifier = "projects"
  name = "projects"
  url = "/projects/"
  weight = 80

  [[menu.navbar]]
  identifier = "misc"
  name = "misc"
  url = "/misc/"
  weight = 90

  [[menu.navbar]]
  identifier = "me"
  name = "me"
  url = "/me/"
  weight = 100
    [[menu.navbar]]
    parent = "me"
    identifier = "links"
    name = "links"
    url = "/me/links"
    weight = 1
    [[menu.navbar]]
    parent = "me"
    identifier = "about_me"
    name = "about me"
    url = "/me/about_me"
    weight = 2

[outputs]
home = ["HTML", "RSS", "JSON"]
